name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Test application
      run: pytest tests/test_app.py
    - name: Build and push Docker image
      if: success()
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login $REGISTRY -u ${{ github.repository_owner }} -p "$GITHUB_TOKEN"
        docker build -t $REGISTRY/$IMAGE_NAME .
        docker push $REGISTRY/$IMAGE_NAME:latest